/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fi.korvala;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        HackAssembler classUnderTest = new HackAssembler();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
